<?php

return array(
	'ms_core_date_su' => 'Вс.',
	'ms_core_date_mo' => 'Пн.',
	'ms_core_date_tu' => 'Вт.',
	'ms_core_date_we' => 'Ср.',
	'ms_core_date_th' => 'Чт.',
	'ms_core_date_fr' => 'Пт.',
	'ms_core_date_st' => 'Сб.',

	'ms_core_date_sunday' => 'Воскресенье',
	'ms_core_date_monday' => 'Понедельник',
	'ms_core_date_tuesday' => 'Вторник',
	'ms_core_date_wednesday' => 'Среда',
	'ms_core_date_thursday' => 'Четверг',
	'ms_core_date_friday' => 'Пятница',
	'ms_core_date_saturday' => 'Суббота',

	'ms_core_date_january' => 'Январь',
	'ms_core_date_february' => 'Февраль',
	'ms_core_date_march' => 'Март',
	'ms_core_date_april' => 'Апрель',
	'ms_core_date_may' => 'Май',
	'ms_core_date_june' => 'Июнь',
	'ms_core_date_july' => 'Июль',
	'ms_core_date_august' => 'Август',
	'ms_core_date_september' => 'Сентябрь',
	'ms_core_date_october' => 'Октябрь',
	'ms_core_date_november' => 'Ноябрь',
	'ms_core_date_december' => 'Декабрь',

	'ms_core_date_accusative_january' => 'января',
	'ms_core_date_accusative_february' => 'февраля',
	'ms_core_date_accusative_march' => 'марта',
	'ms_core_date_accusative_april' => 'апреля',
	'ms_core_date_accusative_may' => 'мая',
	'ms_core_date_accusative_june' => 'июня',
	'ms_core_date_accusative_july' => 'июля',
	'ms_core_date_accusative_august' => 'августа',
	'ms_core_date_accusative_september' => 'сентября',
	'ms_core_date_accusative_october' => 'октября',
	'ms_core_date_accusative_november' => 'ноября',
	'ms_core_date_accusative_december' => 'декабря',

	'ms_core_date_short_jan' => 'янв',
	'ms_core_date_short_feb' => 'фев',
	'ms_core_date_short_mar' => 'мар',
	'ms_core_date_short_apr' => 'апр',
	'ms_core_date_short_may' => 'мая',
	'ms_core_date_short_jun' => 'июн',
	'ms_core_date_short_jul' => 'июл',
	'ms_core_date_short_aug' => 'авг',
	'ms_core_date_short_sep' => 'сен',
	'ms_core_date_short_oct' => 'окт',
	'ms_core_date_short_nov' => 'ноя',
	'ms_core_date_short_dec' => 'дек'
);