<?php

return array(
	'ms_core_alpha_big_a' => 'А',
	'ms_core_alpha_big_b' => 'Б',
	'ms_core_alpha_big_v' => 'В',
	'ms_core_alpha_big_g' => 'Г',
	'ms_core_alpha_big_d' => 'Д',
	'ms_core_alpha_big_ye' => 'Е',
	'ms_core_alpha_big_yo' => 'Ё',
	'ms_core_alpha_big_j' => 'Ж',
	'ms_core_alpha_big_z' => 'З',
	'ms_core_alpha_big_i' => 'И',
	'ms_core_alpha_big_iy' => 'Й',
	'ms_core_alpha_big_k' => 'К',
	'ms_core_alpha_big_l' => 'Л',
	'ms_core_alpha_big_m' => 'М',
	'ms_core_alpha_big_n' => 'Н',
	'ms_core_alpha_big_o' => 'О',
	'ms_core_alpha_big_p' => 'П',
	'ms_core_alpha_big_r' => 'Р',
	'ms_core_alpha_big_s' => 'С',
	'ms_core_alpha_big_t' => 'Т',
	'ms_core_alpha_big_u' => 'У',
	'ms_core_alpha_big_f' => 'Ф',
	'ms_core_alpha_big_h' => 'Х',
	'ms_core_alpha_big_c' => 'Ц',
	'ms_core_alpha_big_ch' => 'Ч',
	'ms_core_alpha_big_sh' => 'Ш',
	'ms_core_alpha_big_sch' => 'Щ',
	'ms_core_alpha_big_hard' => 'Ъ',
	'ms_core_alpha_big_ji' => 'Ы',
	'ms_core_alpha_big_soft' => 'Ь',
	'ms_core_alpha_big_ae' => 'Э',
	'ms_core_alpha_big_yu' => 'Ю',
	'ms_core_alpha_big_ya' => 'Я',

	'ms_core_alpha_a' => 'а',
	'ms_core_alpha_b' => 'б',
	'ms_core_alpha_v' => 'в',
	'ms_core_alpha_g' => 'г',
	'ms_core_alpha_d' => 'д',
	'ms_core_alpha_ye' => 'е',
	'ms_core_alpha_yo' => 'ё',
	'ms_core_alpha_j' => 'ж',
	'ms_core_alpha_z' => 'з',
	'ms_core_alpha_i' => 'и',
	'ms_core_alpha_iy' => 'й',
	'ms_core_alpha_k' => 'к',
	'ms_core_alpha_l' => 'л',
	'ms_core_alpha_m' => 'м',
	'ms_core_alpha_n' => 'н',
	'ms_core_alpha_o' => 'о',
	'ms_core_alpha_p' => 'п',
	'ms_core_alpha_r' => 'р',
	'ms_core_alpha_s' => 'с',
	'ms_core_alpha_t' => 'т',
	'ms_core_alpha_u' => 'у',
	'ms_core_alpha_f' => 'ф',
	'ms_core_alpha_h' => 'х',
	'ms_core_alpha_c' => 'ц',
	'ms_core_alpha_ch' => 'ч',
	'ms_core_alpha_sh' => 'ш',
	'ms_core_alpha_sch' => 'щ',
	'ms_core_alpha_hard' => 'ъ',
	'ms_core_alpha_ji' => 'ы',
	'ms_core_alpha_soft' => 'ь',
	'ms_core_alpha_ae' => 'э',
	'ms_core_alpha_yu' => 'ю',
	'ms_core_alpha_ya' => 'я',

	'ms_core_tools_day1' => 'день',
	'ms_core_tools_day2' => 'дня',
	'ms_core_tools_day3' => 'дней'


);